# Camera
BOARD_CAMERA_SENSORS := s5k4h5_8226 imx175
BOARD_GLOBAL_CFLAGS += -DCAMERA_VENDOR_L_COMPAT

TARGET_NEEDS_PLATFORM_TEXT_RELOCATIONS := true
TARGET_USE_VENDOR_CAMERA_EXT := true
USE_DEVICE_SPECIFIC_CAMERA := true
TARGET_HAS_LEGACY_CAMERA_HAL1 := true
